Repository puppetlabs/beaker-puppet, pull requests merged in 2022-03, with the labels that each got.

#177 Igrore files at the root level only
  lib/beaker-puppet/install_utils/module_utils.rb
Labels: enhancement

#181 Release 1.24.0
  CHANGELOG.md
  lib/beaker-puppet/version.rb
Labels: skip-changelog

#182 (PA-4331) Add a step for updating Solaris CA Keystore
  setup/common/003_solaris_cert_fix.rb
  tasks/ci.rake
Labels: enhancement

#184 Release 1.25.0
  CHANGELOG.md
  lib/beaker-puppet/version.rb
Labels: skip-changelog

#186 (maint) Adds CA to Solaris 11 SPARC setup
  setup/common/003_solaris_cert_fix.rb
Labels: enhancement

#188 (maint) Fixes Solaris cert setup step
  setup/common/003_solaris_cert_fix.rb
Labels: bug

#189 Release 1.26.1
  CHANGELOG.md
  lib/beaker-puppet/version.rb
Labels: skip-changelog
