Repository puppetlabs/beaker-puppet, pull requests merged in 2024-02, with the labels that each got.

#239 Add the ability to install puppet-agent from a local dev build
  setup/aio/010_Install_Puppet_Agent.rb
Labels: enhancement

#240 Beaker 5 compatibility
  acceptance/tests/stub_host.rb
  beaker-puppet.gemspec
  lib/beaker-puppet/helpers/puppet_helpers.rb
  lib/beaker-puppet/install_utils/foss_utils.rb
  lib/beaker-puppet/install_utils/puppet_utils.rb
  setup/common/040_ValidateSignCert.rb
  spec/beaker-puppet/helpers/puppet_helpers_spec.rb
  spec/beaker-puppet/install_utils/foss_utils_spec.rb
  spec/beaker-puppet/install_utils/puppet_utils_spec.rb
Labels: backwards-incompatible

#242 Move to Puppet release GitHub Actions
  .github/workflows/auto_release_prep.yml
  .github/workflows/release.yml
Labels: skip-changelog

#243 Add release prep script
  release-prep.sh
Labels: skip-changelog

#232 fix beaker exec when called from bundle exec
  tasks/ci.rake
Labels: bug

#245 Update release-prep script
  release-prep.sh
Labels: skip-changelog

#246 Add changelog generator configuration file
  .github_changelog_generator
Labels: skip-changelog

#247 Update excluded label to "maintenance"
  .github_changelog_generator
Labels: maintenance

#248 Release prep
  .github/workflows/auto_release_prep.yml
  .github/workflows/release.yml
  CHANGELOG.md
  lib/beaker-puppet/version.rb
Labels: maintenance
